version = "0.2.0-rc+20230901"
authors = ["Peter Huene <peter@huene.dev>"]
categories = ["wasm", "wasi", "component-model"]
description = "The WIT package for WASI file system."
license = "Apache-2.0"
homepage = "https://github.com/webAssembly/wasi-filesystem"
repository = "https://github.com/webAssembly/wasi-filesystem"

[dependencies]
"wasi:clocks" = "0.2.0-rc"
"wasi:io" = "0.2.0-rc"

[registries]
default = "https://preview-registry.bytecodealliance.org/"
